/*
 * LEAKED BY DISCORD.GG/ENIGMALEAKS
 * LEAKED BY DISCORD.GG/ENIGMALEAKS
 * LEAKED BY DISCORD.GG/ENIGMALEAKS
 * LEAKED BY DISCORD.GG/ENIGMALEAKS
 * LEAKED BY DISCORD.GG/ENIGMALEAKS
 * LEAKED BY DISCORD.GG/ENIGMALEAKS
 * LEAKED BY DISCORD.GG/ENIGMALEAKS
 * LEAKED BY DISCORD.GG/ENIGMALEAKS
 * LEAKED BY DISCORD.GG/ENIGMALEAKS
 * LEAKED BY DISCORD.GG/ENIGMALEAKS
 * LEAKED BY DISCORD.GG/ENIGMALEAKS
 * LEAKED BY DISCORD.GG/ENIGMALEAKS
 * LEAKED BY DISCORD.GG/ENIGMALEAKS
 * LEAKED BY DISCORD.GG/ENIGMALEAKS
 * LEAKED BY DISCORD.GG/ENIGMALEAKS
 * LEAKED BY DISCORD.GG/ENIGMALEAKS
 * LEAKED BY DISCORD.GG/ENIGMALEAKS
 * LEAKED BY DISCORD.GG/ENIGMALEAKS
 * LEAKED BY DISCORD.GG/ENIGMALEAKS
 * LEAKED BY DISCORD.GG/ENIGMALEAKS
 * LEAKED BY DISCORD.GG/ENIGMALEAKS
 * LEAKED BY DISCORD.GG/ENIGMALEAKS
 * LEAKED BY DISCORD.GG/ENIGMALEAKS
 * LEAKED BY DISCORD.GG/ENIGMALEAKS
 * LEAKED BY DISCORD.GG/ENIGMALEAKS
 * LEAKED BY DISCORD.GG/ENIGMALEAKS
 * LEAKED BY DISCORD.GG/ENIGMALEAKS
 * LEAKED BY DISCORD.GG/ENIGMALEAKS
 * LEAKED BY DISCORD.GG/ENIGMALEAKS
 * LEAKED BY DISCORD.GG/ENIGMALEAKS
 * LEAKED BY DISCORD.GG/ENIGMALEAKS
 * LEAKED BY DISCORD.GG/ENIGMALEAKS
 * LEAKED BY DISCORD.GG/ENIGMALEAKS
 * LEAKED BY DISCORD.GG/ENIGMALEAKS
 * LEAKED BY DISCORD.GG/ENIGMALEAKS
 * LEAKED BY DISCORD.GG/ENIGMALEAKS
 * LEAKED BY DISCORD.GG/ENIGMALEAKS
 * LEAKED BY DISCORD.GG/ENIGMALEAKS
 * LEAKED BY DISCORD.GG/ENIGMALEAKS
 * LEAKED BY DISCORD.GG/ENIGMALEAKS
 * LEAKED BY DISCORD.GG/ENIGMALEAKS
 * LEAKED BY DISCORD.GG/ENIGMALEAKS
 * LEAKED BY DISCORD.GG/ENIGMALEAKS
 * LEAKED BY DISCORD.GG/ENIGMALEAKS
 * LEAKED BY DISCORD.GG/ENIGMALEAKS
 * LEAKED BY DISCORD.GG/ENIGMALEAKS
 * LEAKED BY DISCORD.GG/ENIGMALEAKS
 * LEAKED BY DISCORD.GG/ENIGMALEAKS
 * LEAKED BY DISCORD.GG/ENIGMALEAKS
 * LEAKED BY DISCORD.GG/ENIGMALEAKS
 * LEAKED BY DISCORD.GG/ENIGMALEAKS
 */

// LEAKED BY DISCORD.GG/ENIGMALEAKS
// LEAKED BY DISCORD.GG/ENIGMALEAKS
// LEAKED BY DISCORD.GG/ENIGMALEAKS
// LEAKED BY DISCORD.GG/ENIGMALEAKS
// LEAKED BY DISCORD.GG/ENIGMALEAKS
// LEAKED BY DISCORD.GG/ENIGMALEAKS
// LEAKED BY DISCORD.GG/ENIGMALEAKS
// LEAKED BY DISCORD.GG/ENIGMALEAKS
// LEAKED BY DISCORD.GG/ENIGMALEAKS
// LEAKED BY DISCORD.GG/ENIGMALEAKS
// LEAKED BY DISCORD.GG/ENIGMALEAKS
// LEAKED BY DISCORD.GG/ENIGMALEAKS
// LEAKED BY DISCORD.GG/ENIGMALEAKS
// LEAKED BY DISCORD.GG/ENIGMALEAKS
// LEAKED BY DISCORD.GG/ENIGMALEAKS
// LEAKED BY DISCORD.GG/ENIGMALEAKS
// LEAKED BY DISCORD.GG/ENIGMALEAKS
// LEAKED BY DISCORD.GG/ENIGMALEAKS
// LEAKED BY DISCORD.GG/ENIGMALEAKS
// LEAKED BY DISCORD.GG/ENIGMALEAKS
// LEAKED BY DISCORD.GG/ENIGMALEAKS
// LEAKED BY DISCORD.GG/ENIGMALEAKS
// LEAKED BY DISCORD.GG/ENIGMALEAKS
// LEAKED BY DISCORD.GG/ENIGMALEAKS
// LEAKED BY DISCORD.GG/ENIGMALEAKS
// LEAKED BY DISCORD.GG/ENIGMALEAKS
// LEAKED BY DISCORD.GG/ENIGMALEAKS
// LEAKED BY DISCORD.GG/ENIGMALEAKS
// LEAKED BY DISCORD.GG/ENIGMALEAKS
// LEAKED BY DISCORD.GG/ENIGMALEAKS
// LEAKED BY DISCORD.GG/ENIGMALEAKS
// LEAKED BY DISCORD.GG/ENIGMALEAKS
// LEAKED BY DISCORD.GG/ENIGMALEAKS
// LEAKED BY DISCORD.GG/ENIGMALEAKS
// LEAKED BY DISCORD.GG/ENIGMALEAKS
// LEAKED BY DISCORD.GG/ENIGMALEAKS
// LEAKED BY DISCORD.GG/ENIGMALEAKS
// LEAKED BY DISCORD.GG/ENIGMALEAKS
// LEAKED BY DISCORD.GG/ENIGMALEAKS
// LEAKED BY DISCORD.GG/ENIGMALEAKS
// LEAKED BY DISCORD.GG/ENIGMALEAKS
// LEAKED BY DISCORD.GG/ENIGMALEAKS
// LEAKED BY DISCORD.GG/ENIGMALEAKS
// LEAKED BY DISCORD.GG/ENIGMALEAKS
// LEAKED BY DISCORD.GG/ENIGMALEAKS
// LEAKED BY DISCORD.GG/ENIGMALEAKS
// LEAKED BY DISCORD.GG/ENIGMALEAKS
// LEAKED BY DISCORD.GG/ENIGMALEAKS
// LEAKED BY DISCORD.GG/ENIGMALEAKS

#pragma once
#include <d3d11.h>
#include "imgui/imgui.h"

namespace window {
    extern ImVec2 size;
    extern float rounding;
}

namespace ui {
    extern ImFont* font_title;

    void initialize();
    void render();
    void shutdown();
}
